name: Build and Publish Console App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # Adjust according to your .NET version

    - name: Restore dependencies
      working-directory: src
      run: dotnet restore

    - name: Build and Publish
      working-directory: src
      run: dotnet publish -r win-x86 -c Release /p:PublishSingleFile=true /p:SelfContained=true /p:PublishTrimmed=false -o ./output

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ConsoleAppExecutable
        path: ./src/output
